package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"os"
	"path/filepath"
	"time"
)

const outFile = "internal/beaconhunter/generated_tls.go"

func main() {
	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		die(err)
	}
	caTmpl := &x509.Certificate{
		SerialNumber:          randomSerial(),
		Subject:               pkix.Name{CommonName: "ProxyWatch CA"},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().AddDate(10, 0, 0),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		IsCA:                  true,
		BasicConstraintsValid: true,
	}
	caDER, err := x509.CreateCertificate(rand.Reader, caTmpl, caTmpl, &caKey.PublicKey, caKey)
	if err != nil {
		die(err)
	}

	caCertPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: caDER})
	caKeyDER, err := x509.MarshalECPrivateKey(caKey)
	if err != nil {
		die(err)
	}
	caKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: caKeyDER})

	if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
		die(err)
	}

	f, err := os.Create(outFile)
	if err != nil {
		die(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by scripts/gen_tls.go; DO NOT EDIT.")
	fmt.Fprintln(f, "package beaconhunter")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "const (")
	fmt.Fprintf(f, "  generatedCACertPEM = `%s`\n", string(caCertPEM))
	fmt.Fprintf(f, "  generatedCAKeyPEM = `%s`\n", string(caKeyPEM))
	fmt.Fprintln(f, ")")
}

func randomSerial() *big.Int {
	serialLimit := new(big.Int).Lsh(big.NewInt(1), 62)
	serial, err := rand.Int(rand.Reader, serialLimit)
	if err != nil {
		return big.NewInt(1)
	}
	return serial
}

func die(err error) {
	fmt.Fprintln(os.Stderr, "gen_tls:", err)
	os.Exit(1)
}
